name: '${pluginName}'
version: '${version}'
main: org.yuemi.villagertweaks.plugin.VillagerTweaksPlugin
authors: [${authors}]
contributors: [${contributors}]
api-version: '${apiVersion}'

bstats-id: '${bstatsPluginId}'

commands:
  villagertweaks:
    description: Main command for VillagerTweaks.
    aliases: [vt]
    permission: villagertweaks.command.use
    permission-message: You do not have permission to use this command!

permissions:
  villagertweaks.command.use:
    description: Allows using the main command.
    default: true
  villagertweaks.command.reload:
    description: Allows reloading the configuration.
    default: op
